// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import CoreData;
@import CoreBluetooth;
@import CoreLocation;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
typedef SWIFT_ENUM(NSInteger, ActionType) {
  ActionTypeMacAddress = 0,
  ActionTypeDeviceInfo = 1,
  ActionTypeLiveData = 2,
  ActionTypeFuncTable = 3,
};

@class User;
@class Device;
@class DeviceFunction;
@class SportEverydayData;
@class SleepEverydayData;
@class HeartRateEverydayData;

SWIFT_CLASS("_TtC8AngelFit12AngelManager")
@interface AngelManager : NSObject
@property (nonatomic, copy) NSString * _Nullable macAddress;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable accessoryId;
+ (AngelManager * _Nullable)share SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)getUserinfoWithClosure:(SWIFT_NOESCAPE void (^ _Nonnull)(User * _Nullable))closure;
- (void)getDevice:(NSString * _Nullable)accessoryId closure:(void (^ _Nonnull)(Device * _Nullable))closure;
- (void)getMacAddressFromBandWithClosure:(void (^ _Nonnull)(int16_t, NSString * _Nonnull))closure;
- (void)getFuncTable:(NSString * _Nullable)accessoryId closure:(void (^ _Nonnull)(DeviceFunction * _Nullable))closure;
- (void)getLiveDataFromBandWithClosure:(void (^ _Nonnull)(int16_t, id _Nullable))closure;
- (void)setUpdateWithClosure:(void (^ _Nonnull)(BOOL))closure;
- (void)setBind:(BOOL)bind closure:(void (^ _Nonnull)(BOOL))closure;
- (void)setDateWithDate:(NSDate * _Nonnull)date closure:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL))closure;
- (void)setCamera:(BOOL)open closure:(void (^ _Nonnull)(BOOL))closure;
- (void)setFindPhone:(BOOL)open timeOut:(uint8_t)timeOut accessoryId:(NSString * _Nullable)accessoryId closure:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL))closure;
- (void)setGhostWithClosure:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL))closure;
- (void)setQuickSOS:(BOOL)open accessoryId:(NSString * _Nullable)accessoryId closure:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL))closure;
- (void)setRestartWithClosure:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL))closure;
- (void)setWristRecognition:(BOOL)open lightDuring:(uint8_t)lightDuring closure:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL))closure;
- (void)setSynchronizationHealthData:(NSString * _Nullable)accessoryId closure:(void (^ _Nonnull)(BOOL, int16_t))closure;
- (void)getSportData:(NSString * _Nullable)accessoryId date:(NSDate * _Nonnull)date offset:(NSInteger)offset closure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSArray<SportEverydayData *> * _Nonnull))closure;
- (void)getSleepData:(NSString * _Nullable)accessoryId date:(NSDate * _Nonnull)date offset:(NSInteger)offset closure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSArray<SleepEverydayData *> * _Nonnull))closure;
- (void)getHeartRateData:(NSString * _Nullable)accessoryId date:(NSDate * _Nonnull)date offset:(NSInteger)offset closure:(SWIFT_NOESCAPE void (^ _Nonnull)(NSArray<HeartRateEverydayData *> * _Nonnull))closure;
- (void)setSynchronizationConfigWithClosure:(void (^ _Nonnull)(BOOL))closure;
- (void)getNoticeStatus:(void (^ _Nonnull)(BOOL))closure;
@end


@interface AngelManager (SWIFT_EXTENSION(AngelFit))
@end

typedef SWIFT_ENUM(NSInteger, BandMode) {
  BandModeUnbind = 0,
  BandModeBind = 1,
  BandModeLevelup = 2,
};

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("BloodPressureEverydayData")
@interface BloodPressureEverydayData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class BloodPressureEverydayDataItem;
@class NSSet;

@interface BloodPressureEverydayData (SWIFT_EXTENSION(AngelFit))
- (void)addBloodPressureEverydayDataItemListObject:(BloodPressureEverydayDataItem * _Nonnull)value;
- (void)removeBloodPressureEverydayDataItemListObject:(BloodPressureEverydayDataItem * _Nonnull)value;
- (void)addBloodPressureEverydayDataItemList:(NSSet * _Nonnull)values;
- (void)removeBloodPressureEverydayDataItemList:(NSSet * _Nonnull)values;
@end

@class NSDate;

@interface BloodPressureEverydayData (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t avgDiastolicPressure;
@property (nonatomic) int16_t avgSystolicPressure;
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int64_t objectId;
@property (nonatomic) int16_t offset;
@property (nonatomic, strong) NSSet * _Nullable bloodPressureEverydayDataItemList;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("BloodPressureEverydayDataItem")
@interface BloodPressureEverydayDataItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface BloodPressureEverydayDataItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t diastolicPressure;
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t systolicPressure;
@property (nonatomic) int16_t toLastMinutes;
@property (nonatomic, strong) BloodPressureEverydayData * _Nullable bloodPressureEverydayData;
@end


@interface CBPeripheral (SWIFT_EXTENSION(AngelFit))
@end

typedef SWIFT_ENUM(NSInteger, CommondType) {
  CommondTypeSetTime = 0,
};


SWIFT_CLASS_NAMED("Device")
@interface Device : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addHeartRateEverydayDataListObject:(HeartRateEverydayData * _Nonnull)value;
- (void)removeHeartRateEverydayDataListObject:(HeartRateEverydayData * _Nonnull)value;
- (void)addHeartRateEverydayDataList:(NSSet * _Nonnull)values;
- (void)removeHeartRateEverydayDataList:(NSSet * _Nonnull)values;
@end


@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addSleepEverydayDataListObject:(SleepEverydayData * _Nonnull)value;
- (void)removeSleepEverydayDataListObject:(SleepEverydayData * _Nonnull)value;
- (void)addSleepEverydayDataList:(NSSet * _Nonnull)values;
- (void)removeSleepEverydayDataList:(NSSet * _Nonnull)values;
@end


@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addSportEverydayDataListObject:(SportEverydayData * _Nonnull)value;
- (void)removeSportEverydayDataListObject:(SportEverydayData * _Nonnull)value;
- (void)addSportEverydayDataList:(NSSet * _Nonnull)values;
- (void)removeSportEverydayDataList:(NSSet * _Nonnull)values;
@end

@class UserActivity;

@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addUserActivityListObject:(UserActivity * _Nonnull)value;
- (void)removeUserActivityListObject:(UserActivity * _Nonnull)value;
- (void)addUserActivityList:(NSSet * _Nonnull)values;
- (void)removeUserActivityList:(NSSet * _Nonnull)values;
@end


@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addBloodPressureEverydayDataListObject:(BloodPressureEverydayData * _Nonnull)value;
- (void)removeBloodPressureEverydayDataListObject:(BloodPressureEverydayData * _Nonnull)value;
- (void)addBloodPressureEverydayDataList:(NSSet * _Nonnull)values;
- (void)removeBloodPressureEverydayDataList:(NSSet * _Nonnull)values;
@end

@class DeviceAlarm;

@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addDeviceAlarmListObject:(DeviceAlarm * _Nonnull)value;
- (void)removeDeviceAlarmListObject:(DeviceAlarm * _Nonnull)value;
- (void)addDeviceAlarmList:(NSSet * _Nonnull)values;
- (void)removeDeviceAlarmList:(NSSet * _Nonnull)values;
@end

@class EachTrainningData;

@interface Device (SWIFT_EXTENSION(AngelFit))
- (void)addEachTrainningDataListObject:(EachTrainningData * _Nonnull)value;
- (void)removeEachTrainningDataListObject:(EachTrainningData * _Nonnull)value;
- (void)addEachTrainningDataList:(NSSet * _Nonnull)values;
- (void)removeEachTrainningDataList:(NSSet * _Nonnull)values;
@end

@class DeviceAntiLostSetting;
@class DeviceFunctionAlarm;
@class DeviceFunctionMsgItem;
@class DeviceFunctionSportItem;
@class DeviceFunctionSwitchSetting;
@class DeviceHeartRateMonitorSetting;
@class DeviceLongSitSetting;
@class DeviceMsgNotifySwitch;
@class DeviceSportShortcut;

@interface Device (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, copy) NSString * _Nullable accessoryId;
@property (nonatomic) int16_t batteryLevel;
@property (nonatomic) int64_t batteryLife;
@property (nonatomic) int16_t batteryStatus;
@property (nonatomic, strong) NSDate * _Nullable creativeDate;
@property (nonatomic) BOOL isLogin;
@property (nonatomic) BOOL isPaired;
@property (nonatomic) BOOL isRebooted;
@property (nonatomic, strong) NSDate * _Nullable lastSyncTime;
@property (nonatomic, copy) NSString * _Nullable macAddress;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t runMode;
@property (nonatomic, copy) NSString * _Nullable showName;
@property (nonatomic) int16_t type;
@property (nonatomic) int32_t usageMinutes;
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic) int16_t version;
@property (nonatomic, strong) NSSet * _Nullable bloodPressureEverydayDataList;
@property (nonatomic, strong) NSSet * _Nullable deviceAlarmList;
@property (nonatomic, strong) DeviceAntiLostSetting * _Nullable deviceAntiLostSetting;
@property (nonatomic, strong) DeviceFunction * _Nullable deviceFunction;
@property (nonatomic, strong) DeviceFunctionAlarm * _Nullable deviceFunctionAlarm;
@property (nonatomic, strong) DeviceFunctionMsgItem * _Nullable deviceFunctionMsgItem;
@property (nonatomic, strong) DeviceFunctionSportItem * _Nullable deviceFunctionSportItem;
@property (nonatomic, strong) DeviceFunctionSwitchSetting * _Nullable deviceFunctionSwitchSetting;
@property (nonatomic, strong) DeviceHeartRateMonitorSetting * _Nullable deviceHeartRateMonitorSetting;
@property (nonatomic, strong) DeviceLongSitSetting * _Nullable deviceLongSitSetting;
@property (nonatomic, strong) DeviceMsgNotifySwitch * _Nullable deviceMsgNotifySwitch;
@property (nonatomic, strong) DeviceSportShortcut * _Nullable deviceSportShortcut;
@property (nonatomic, strong) NSSet * _Nullable eachTrainningDataList;
@property (nonatomic, strong) NSSet * _Nullable heartRateEverydayDataList;
@property (nonatomic, strong) NSSet * _Nullable sleepEverydayDataList;
@property (nonatomic, strong) NSSet * _Nullable sportEverydayDataList;
@property (nonatomic, strong) User * _Nullable user;
@property (nonatomic, strong) NSSet * _Nullable userActivityList;
@end


SWIFT_CLASS_NAMED("DeviceAlarm")
@interface DeviceAlarm : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceAlarm (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t alarmId;
@property (nonatomic) int16_t hour;
@property (nonatomic) BOOL isSynced;
@property (nonatomic) int16_t minute;
@property (nonatomic) BOOL repetition;
@property (nonatomic) BOOL showStatus;
@property (nonatomic) int16_t snoozeDurationMinute;
@property (nonatomic) int16_t type;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceAntiLostSetting")
@interface DeviceAntiLostSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceAntiLostSetting (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t delaySeconds;
@property (nonatomic) int16_t disconnectAnti;
@property (nonatomic) int16_t disconnectAntiDelaySeconds;
@property (nonatomic) int16_t mode;
@property (nonatomic) int16_t repetition;
@property (nonatomic) int16_t rss;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceFunction")
@interface DeviceFunction : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceFunction (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) BOOL haveAlarm;
@property (nonatomic) BOOL haveAllMsgNotification;
@property (nonatomic) BOOL haveAncs;
@property (nonatomic) BOOL haveAntiLost;
@property (nonatomic) BOOL haveCallContact;
@property (nonatomic) BOOL haveCallNotification;
@property (nonatomic) BOOL haveCallNumber;
@property (nonatomic) BOOL haveCameraControl;
@property (nonatomic) BOOL haveFindPhone;
@property (nonatomic) BOOL haveHeartRateMonitor;
@property (nonatomic) BOOL haveHeartRateMonitorControl;
@property (nonatomic) BOOL haveLogin;
@property (nonatomic) BOOL haveLongSit;
@property (nonatomic) BOOL haveMsgContent;
@property (nonatomic) BOOL haveMultiSport;
@property (nonatomic) BOOL haveNotDisturbMode;
@property (nonatomic) BOOL haveOta;
@property (nonatomic) BOOL havePedometer;
@property (nonatomic) BOOL havePlayMusicControl;
@property (nonatomic) BOOL haveRealData;
@property (nonatomic) BOOL haveScreenDisplay180Rotate;
@property (nonatomic) BOOL haveScreenDisplayMode;
@property (nonatomic) BOOL haveShortcutCall;
@property (nonatomic) BOOL haveShortcutReset;
@property (nonatomic) BOOL haveSleepMonitor;
@property (nonatomic) BOOL haveTimeline;
@property (nonatomic) BOOL haveTraininTracking;
@property (nonatomic) BOOL haveWakeScreenOnWristRaise;
@property (nonatomic) BOOL haveWeatherForecast;
@property (nonatomic) BOOL isHeartRateMonitorSilent;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceFunctionAlarm")
@interface DeviceFunctionAlarm : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceFunctionAlarm (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) BOOL isCustom;
@property (nonatomic) BOOL isDate;
@property (nonatomic) BOOL isGetup;
@property (nonatomic) BOOL isMeeting;
@property (nonatomic) BOOL isParty;
@property (nonatomic) BOOL isSleep;
@property (nonatomic) BOOL isTakePill;
@property (nonatomic) BOOL isWorkout;
@property (nonatomic) int16_t maxNumber;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceFunctionMsgItem")
@interface DeviceFunctionMsgItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceFunctionMsgItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) BOOL haveAlarmEvent;
@property (nonatomic) BOOL haveCalendarEvent;
@property (nonatomic) BOOL haveEmail;
@property (nonatomic) BOOL haveFacebook;
@property (nonatomic) BOOL haveInstagram;
@property (nonatomic) BOOL haveLinkedIn;
@property (nonatomic) BOOL haveMessenger;
@property (nonatomic) BOOL haveOther;
@property (nonatomic) BOOL havePokeman;
@property (nonatomic) BOOL haveQQ;
@property (nonatomic) BOOL haveSinaWeibo;
@property (nonatomic) BOOL haveSkype;
@property (nonatomic) BOOL haveSms;
@property (nonatomic) BOOL haveTwitter;
@property (nonatomic) BOOL haveWechat;
@property (nonatomic) BOOL haveWhatsapp;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceFunctionSportItem")
@interface DeviceFunctionSportItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceFunctionSportItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) BOOL haveAerobics;
@property (nonatomic) BOOL haveBadminton;
@property (nonatomic) BOOL haveBaseball;
@property (nonatomic) BOOL haveBasketball;
@property (nonatomic) BOOL haveBike;
@property (nonatomic) BOOL haveClimb;
@property (nonatomic) BOOL haveDance;
@property (nonatomic) BOOL haveDumbell;
@property (nonatomic) BOOL haveEllipse;
@property (nonatomic) BOOL haveFootball;
@property (nonatomic) BOOL haveGolf;
@property (nonatomic) BOOL haveHike;
@property (nonatomic) BOOL haveOther;
@property (nonatomic) BOOL havePingPong;
@property (nonatomic) BOOL havePushUp;
@property (nonatomic) BOOL haveRun;
@property (nonatomic) BOOL haveSitUp;
@property (nonatomic) BOOL haveSki;
@property (nonatomic) BOOL haveSpinning;
@property (nonatomic) BOOL haveSwim;
@property (nonatomic) BOOL haveTennis;
@property (nonatomic) BOOL haveTreadmill;
@property (nonatomic) BOOL haveVolleyball;
@property (nonatomic) BOOL haveWalk;
@property (nonatomic) BOOL haveWeight;
@property (nonatomic) BOOL haveWorkout;
@property (nonatomic) BOOL haveYoga;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceFunctionSwitchSetting")
@interface DeviceFunctionSwitchSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceFunctionSwitchSetting (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t alarmOnCount;
@property (nonatomic) int16_t callNotifyDelaySeconds;
@property (nonatomic) BOOL isAlarmOn;
@property (nonatomic) BOOL isAntiLostOn;
@property (nonatomic) BOOL isCallNotifyOn;
@property (nonatomic) BOOL isCameraControlOn;
@property (nonatomic) BOOL isFindPhonesOn;
@property (nonatomic) BOOL isHeartRateMonitorOn;
@property (nonatomic) BOOL isLongSitOn;
@property (nonatomic) BOOL isMusicControlOn;
@property (nonatomic) BOOL isNotDisturbOn;
@property (nonatomic) BOOL isWakeScreenOnWristRaiseOn;
@property (nonatomic) BOOL isWeatherForecastOn;
@property (nonatomic) int16_t screenDisplayMode;
@property (nonatomic) int16_t wakeScreenOnSeconds;
@property (nonatomic) int16_t wearPosition;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceHeartRateMonitorSetting")
@interface DeviceHeartRateMonitorSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceHeartRateMonitorSetting (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t aerobicThreshold;
@property (nonatomic) int16_t burFatThreshold;
@property (nonatomic) int16_t limitThreshold;
@property (nonatomic) int16_t maxHeartRate;
@property (nonatomic) int16_t workMode;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceLongSitSetting")
@interface DeviceLongSitSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceLongSitSetting (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t endHour;
@property (nonatomic) int16_t endMinute;
@property (nonatomic) int32_t intervalMinute;
@property (nonatomic) int16_t repetition;
@property (nonatomic) int16_t startHour;
@property (nonatomic) int16_t startMinute;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceMsgNotifySwitch")
@interface DeviceMsgNotifySwitch : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceMsgNotifySwitch (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) BOOL isAlarmEventOn;
@property (nonatomic) BOOL isCalendarEventOn;
@property (nonatomic) BOOL isEmailOn;
@property (nonatomic) BOOL isFacebookOn;
@property (nonatomic) BOOL isInstagramOn;
@property (nonatomic) BOOL isLinkedInOn;
@property (nonatomic) BOOL isMainOn;
@property (nonatomic) BOOL isMessengerOn;
@property (nonatomic) BOOL isOtherOn;
@property (nonatomic) BOOL isPokemanOn;
@property (nonatomic) BOOL isQQOn;
@property (nonatomic) BOOL isSinaWeiboOn;
@property (nonatomic) BOOL isSkypeOn;
@property (nonatomic) BOOL isSmsOn;
@property (nonatomic) BOOL isTwitterOn;
@property (nonatomic) BOOL isWechatOn;
@property (nonatomic) BOOL isWhatsapOn;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DeviceSportShortcut")
@interface DeviceSportShortcut : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DeviceSportShortcut (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t shortcut1;
@property (nonatomic) int16_t shortcut2;
@property (nonatomic) int16_t shortcut3;
@property (nonatomic) int16_t shortcut4;
@property (nonatomic) int16_t shortcut5;
@property (nonatomic) int16_t shortcut6;
@property (nonatomic) int16_t shortcut7;
@property (nonatomic) int16_t shortcut8;
@property (nonatomic) int16_t shortcut9;
@property (nonatomic) int16_t shortcut10;
@property (nonatomic) int16_t shortcut11;
@property (nonatomic) int16_t shortcut12;
@property (nonatomic) int16_t shortcut13;
@property (nonatomic) int16_t shortcut14;
@property (nonatomic) int16_t shortcut15;
@property (nonatomic) int16_t shortcut16;
@property (nonatomic, strong) Device * _Nullable device;
@end


SWIFT_CLASS_NAMED("DoctorHaSuggestion")
@interface DoctorHaSuggestion : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class DoctorHaSuggestionFeedback;

@interface DoctorHaSuggestion (SWIFT_EXTENSION(AngelFit))
- (void)addDoctorHaSuggestionFeedbackListObject:(DoctorHaSuggestionFeedback * _Nonnull)value;
- (void)removeDoctorHaSuggestionFeedbackListObject:(DoctorHaSuggestionFeedback * _Nonnull)value;
- (void)addDoctorHaSuggestionFeedbackList:(NSSet * _Nonnull)values;
- (void)removeDoctorHaSuggestionFeedbackList:(NSSet * _Nonnull)values;
@end


@interface DoctorHaSuggestion (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int64_t id;
@property (nonatomic) int16_t lastLikeEmotion;
@property (nonatomic, copy) NSString * _Nullable linkedTo;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, strong) NSSet * _Nullable doctorHaSuggestionFeedbackList;
@property (nonatomic, strong) UserActivity * _Nullable userActivity;
@end


SWIFT_CLASS_NAMED("DoctorHaSuggestionFeedback")
@interface DoctorHaSuggestionFeedback : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface DoctorHaSuggestionFeedback (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int64_t advisorId;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) int16_t type;
@property (nonatomic, strong) DoctorHaSuggestion * _Nullable doctorHaSuggestion;
@end


SWIFT_CLASS_NAMED("EachTrainningData")
@interface EachTrainningData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class EachTrainningGPSLoggerItem;

@interface EachTrainningData (SWIFT_EXTENSION(AngelFit))
- (void)addGpsLoggerItemsObject:(EachTrainningGPSLoggerItem * _Nonnull)value;
- (void)removeGpsLoggerItemsObject:(EachTrainningGPSLoggerItem * _Nonnull)value;
- (void)addGpsLoggerItems:(NSSet * _Nonnull)values;
- (void)removeGpsLoggerItems:(NSSet * _Nonnull)values;
@end

@class EachTrainningHeartRateItem;

@interface EachTrainningData (SWIFT_EXTENSION(AngelFit))
- (void)addHeartRateActivityItemsObject:(EachTrainningHeartRateItem * _Nonnull)value;
- (void)removeHeartRateActivityItemsObject:(EachTrainningHeartRateItem * _Nonnull)value;
- (void)addHeartRateActivityItems:(NSSet * _Nonnull)values;
- (void)removeHeartRateActivityItems:(NSSet * _Nonnull)values;
@end

@class EachTrainningStepItem;

@interface EachTrainningData (SWIFT_EXTENSION(AngelFit))
- (void)addStepPreMinuteItemsObject:(EachTrainningStepItem * _Nonnull)value;
- (void)removeStepPreMinuteItemsObject:(EachTrainningStepItem * _Nonnull)value;
- (void)addStepPreMinuteItems:(NSSet * _Nonnull)values;
- (void)removeStepPreMinuteItems:(NSSet * _Nonnull)values;
@end


@interface EachTrainningData (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t aerobicMinutes;
@property (nonatomic) int16_t averageHeartRate;
@property (nonatomic) int16_t burnFatMinutes;
@property (nonatomic) int32_t calories;
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int32_t distances100TimesM;
@property (nonatomic) int32_t durationS;
@property (nonatomic) BOOL hasGPSLogger;
@property (nonatomic) BOOL hasHeartRate;
@property (nonatomic) BOOL hasStepItems;
@property (nonatomic) int16_t heartRateItemIntervalSeconds;
@property (nonatomic) int16_t limitMinutes;
@property (nonatomic) int16_t mapSource;
@property (nonatomic) int16_t maxHeartRate;
@property (nonatomic) int64_t objectId;
@property (nonatomic, strong) NSDate * _Nullable startedAt;
@property (nonatomic) int32_t steps;
@property (nonatomic) int16_t stepsIntervalSeconds;
@property (nonatomic) int16_t type;
@property (nonatomic, strong) Device * _Nullable device;
@property (nonatomic, strong) NSSet * _Nullable gpsLoggerItems;
@property (nonatomic, strong) NSSet * _Nullable heartRateActivityItems;
@property (nonatomic, strong) NSSet * _Nullable stepPreMinuteItems;
@end


SWIFT_CLASS_NAMED("EachTrainningGPSLoggerItem")
@interface EachTrainningGPSLoggerItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface EachTrainningGPSLoggerItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t id;
@property (nonatomic) double latitude;
@property (nonatomic) double longtitude;
@property (nonatomic, strong) NSDate * _Nullable timeStamp;
@property (nonatomic, strong) EachTrainningData * _Nullable eachTrainningData;
@end


SWIFT_CLASS_NAMED("EachTrainningHeartRateItem")
@interface EachTrainningHeartRateItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface EachTrainningHeartRateItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t id;
@property (nonatomic) int32_t value;
@property (nonatomic, strong) EachTrainningData * _Nullable eachTrainningData;
@end


SWIFT_CLASS_NAMED("EachTrainningStepItem")
@interface EachTrainningStepItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface EachTrainningStepItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t steps;
@property (nonatomic, strong) EachTrainningData * _Nullable eachTrainningData;
@end


SWIFT_CLASS_NAMED("Goal")
@interface Goal : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Goal (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) BOOL isSyncedServer;
@property (nonatomic) int16_t sleepMinutes;
@property (nonatomic) int32_t steps;
@property (nonatomic) int32_t weight10000TimesKG;
@property (nonatomic, strong) User * _Nullable user;
@end

@protocol GodManagerDelegate;

SWIFT_CLASS("_TtC8AngelFit10GodManager")
@interface GodManager : NSObject
@property (nonatomic, strong) id <GodManagerDelegate> _Nullable delegate;
@property (nonatomic) BOOL isAutoReconnect;
@property (nonatomic, readonly) BOOL isScaning;
+ (GodManager * _Nonnull)share SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startScanWithClosure:(void (^ _Nullable)(void))closure;
- (void)stopScan;
- (void)connect:(CBPeripheral * _Nonnull)peripheral;
- (void)disconnect:(CBPeripheral * _Nonnull)peripheral closure:(void (^ _Nonnull)(BOOL))closure;
@end

@class CBCharacteristic;
@class CBService;

@interface GodManager (SWIFT_EXTENSION(AngelFit)) <CBPeripheralDelegate>
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end

@class CBCentralManager;
@class NSNumber;

@interface GodManager (SWIFT_EXTENSION(AngelFit)) <CBCentralManagerDelegate>
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
- (void)centralManager:(CBCentralManager * _Nonnull)central willRestoreState:(NSDictionary<NSString *, id> * _Nonnull)dict;
@end

typedef SWIFT_ENUM(NSInteger, GodManagerConnectState) {
  GodManagerConnectStateConnect = 0,
  GodManagerConnectStateFailed = 1,
  GodManagerConnectStateDisConnect = 2,
};

enum GodManagerState : NSInteger;

SWIFT_PROTOCOL("_TtP8AngelFit18GodManagerDelegate_")
@protocol GodManagerDelegate
- (void)godManagerWithCurrentConnectPeripheral:(CBPeripheral * _Nonnull)peripheral peripheralName:(NSString * _Nonnull)name;
- (void)godManagerWithDidDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral withRSSI:(NSNumber * _Nonnull)RSSI peripheralName:(NSString * _Nonnull)name;
- (void)godManagerWithDidUpdateCentralState:(enum GodManagerState)state;
- (void)godManagerWithDidUpdateConnectState:(enum GodManagerConnectState)state withPeripheral:(CBPeripheral * _Nonnull)peripheral withError:(NSError * _Nullable)error;
- (void)godManagerWithDidConnectedPeripheral:(CBPeripheral * _Nonnull)peripheral connectState:(BOOL)isSuccess;
- (void)godManagerWithBindingPeripheralsUUID:(NSArray<NSString *> * _Nonnull)UUIDList;
@end

typedef SWIFT_ENUM(NSInteger, GodManagerState) {
  GodManagerStateUnknown = 0,
  GodManagerStateResetting = 1,
  GodManagerStateUnsupported = 2,
  GodManagerStateUnauthorized = 3,
  GodManagerStatePoweredOff = 4,
  GodManagerStatePoweredOn = 5,
};

typedef SWIFT_ENUM(NSInteger, HealthDataType) {
  HealthDataTypeSport = 0,
  HealthDataTypeSleep = 1,
  HealthDataTypeHeartRate = 2,
};


SWIFT_CLASS_NAMED("HeartRateEverydayData")
@interface HeartRateEverydayData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class HeartRateEverydayDataItem;

@interface HeartRateEverydayData (SWIFT_EXTENSION(AngelFit))
- (void)addHeartRateEverydayItemListObject:(HeartRateEverydayDataItem * _Nonnull)value;
- (void)removeHeartRateEverydayItemListObject:(HeartRateEverydayDataItem * _Nonnull)value;
- (void)addHeartRateEverydayItemList:(NSSet * _Nonnull)values;
- (void)removeHeartRateEverydayItemList:(NSSet * _Nonnull)values;
@end


@interface HeartRateEverydayData (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t aerobicMinutes;
@property (nonatomic) int16_t aerobicThreshold;
@property (nonatomic) int16_t burnFatMinutes;
@property (nonatomic) int16_t burnFatThreshold;
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int16_t limitMinutes;
@property (nonatomic) int16_t limitThreshold;
@property (nonatomic) int64_t objectId;
@property (nonatomic) int16_t offset;
@property (nonatomic) int16_t silentHeartRate;
@property (nonatomic, strong) Device * _Nullable device;
@property (nonatomic, strong) NSSet * _Nullable heartRateEverydayItemList;
@end


SWIFT_CLASS_NAMED("HeartRateEverydayDataItem")
@interface HeartRateEverydayDataItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface HeartRateEverydayDataItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t toLastMinutes;
@property (nonatomic) int16_t value;
@property (nonatomic, strong) HeartRateEverydayData * _Nullable heartRateEverydayData;
@end

typedef SWIFT_ENUM(NSInteger, HeartRateMode) {
  HeartRateModeManual = 0,
  HeartRateModeAuto = 1,
  HeartRateModeClose = 2,
};


SWIFT_CLASS_NAMED("MindBodyState")
@interface MindBodyState : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface MindBodyState (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int16_t mindBodyState;
@property (nonatomic) int64_t objectId;
@property (nonatomic, strong) User * _Nullable user;
@end


SWIFT_CLASS("_TtC8AngelFit17PeripheralManager")
@interface PeripheralManager : NSObject
+ (PeripheralManager * _Nonnull)share SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nullable UUID;
@property (nonatomic, readonly, strong) CBPeripheral * _Nullable currentPeripheral;
- (NSArray<NSString *> * _Nonnull)selectUUIDStringList SWIFT_WARN_UNUSED_RESULT;
- (BOOL)addWithNewUUIDString:(NSString * _Nonnull)uuidString SWIFT_WARN_UNUSED_RESULT;
- (BOOL)deleteWithUUIDString:(NSString * _Nonnull)uuidString SWIFT_WARN_UNUSED_RESULT;
- (BOOL)selectWithUUIDString:(NSString * _Nonnull)uuidString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SatanManagerDelegate;

SWIFT_CLASS("_TtC8AngelFit12SatanManager")
@interface SatanManager : NSObject
@property (nonatomic, weak) id <SatanManagerDelegate> _Nullable delegate;
+ (SatanManager * _Nullable)share SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
- (void)addTrackWithCoordinate:(CLLocationCoordinate2D)coordinate withInterval:(NSTimeInterval)interval totalDistance:(double)distance childDistance:(double)subDistance;
- (void)resetTrack;
- (void)setSynchronizationActiveData:(NSString * _Nullable)accessoryId closure:(void (^ _Nonnull)(BOOL, int16_t, BOOL))closure;
- (void)getSynchronizationActiveCount:(NSString * _Nullable)accessoryId closure:(void (^ _Nonnull)(uint8_t))closure;
@end

enum SatanManagerState : NSInteger;

SWIFT_PROTOCOL("_TtP8AngelFit20SatanManagerDelegate_")
@protocol SatanManagerDelegate
- (void)satanManagerWithDidUpdateState:(enum SatanManagerState)state;
- (uint32_t)satanManagerDistanceByLocationWithBleDistance:(uint32_t)distance SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)satanManagerDuration SWIFT_WARN_UNUSED_RESULT;
- (void)satanManagerWithDidSwitchingReplyCalories:(uint32_t)calories distance:(uint32_t)distance step:(uint32_t)step curHeartrate:(uint8_t)curHeartrate heartrateSerial:(uint8_t)heartrateSerial available:(BOOL)available heartrateValue:(NSArray<NSNumber *> * _Nonnull)heartrateValue;
@end

typedef SWIFT_ENUM(NSInteger, SatanManagerState) {
  SatanManagerStateStart = 0,
  SatanManagerStatePause = 1,
  SatanManagerStateRestore = 2,
  SatanManagerStateEnd = 3,
};


SWIFT_CLASS_NAMED("SleepEverydayData")
@interface SleepEverydayData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class SleepEverydayDataItem;

@interface SleepEverydayData (SWIFT_EXTENSION(AngelFit))
- (void)addSleepEverydayDataItemListObject:(SleepEverydayDataItem * _Nonnull)value;
- (void)removeSleepEverydayDataItemListObject:(SleepEverydayDataItem * _Nonnull)value;
- (void)addSleepEverydayDataItemList:(NSSet * _Nonnull)values;
- (void)removeSleepEverydayDataItemList:(NSSet * _Nonnull)values;
@end


@interface SleepEverydayData (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int32_t awakeCount;
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int32_t deepSleepCount;
@property (nonatomic) int16_t deepSleepMinutes;
@property (nonatomic) int32_t endedHour;
@property (nonatomic) int32_t endedMinute;
@property (nonatomic) int32_t itemsCount;
@property (nonatomic) int32_t lightSleepCount;
@property (nonatomic) int16_t lightSleepMinutes;
@property (nonatomic) int64_t objectId;
@property (nonatomic) int16_t remSleepMinutes;
@property (nonatomic) int16_t totalMinutes;
@property (nonatomic, strong) Device * _Nullable device;
@property (nonatomic, strong) NSSet * _Nullable sleepEverydayDataItemList;
@end


SWIFT_CLASS_NAMED("SleepEverydayDataItem")
@interface SleepEverydayDataItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface SleepEverydayDataItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t durationsMinute;
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t status;
@property (nonatomic, strong) SleepEverydayData * _Nullable sleepEverydayData;
@end


SWIFT_CLASS_NAMED("SportEverydayData")
@interface SportEverydayData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class SportEverydayDataItem;

@interface SportEverydayData (SWIFT_EXTENSION(AngelFit))
- (void)addSportEverydayDataItemListObject:(SportEverydayDataItem * _Nonnull)value;
- (void)removeSportEverydayDataItemListObject:(SportEverydayDataItem * _Nonnull)value;
- (void)addSportEverydayDataItemList:(NSSet * _Nonnull)values;
- (void)removeSportEverydayDataItemList:(NSSet * _Nonnull)values;
@end


@interface SportEverydayData (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int64_t objectId;
@property (nonatomic) int32_t offset;
@property (nonatomic) int32_t perMinute;
@property (nonatomic) int32_t sportItemCount;
@property (nonatomic) int32_t totalActiveTimeSeconds;
@property (nonatomic) int32_t totalCalories;
@property (nonatomic) int32_t totalDistances;
@property (nonatomic) int32_t totalSteps;
@property (nonatomic, strong) Device * _Nullable device;
@property (nonatomic, strong) NSSet * _Nullable sportEverydayDataItemList;
@end


SWIFT_CLASS_NAMED("SportEverydayDataItem")
@interface SportEverydayDataItem : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface SportEverydayDataItem (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t activeDurationMinutes;
@property (nonatomic) int16_t calories;
@property (nonatomic) int16_t distancesM;
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t mode;
@property (nonatomic) int16_t steps;
@property (nonatomic, strong) SportEverydayData * _Nullable sportEverydayData;
@end


@interface UIViewController (SWIFT_EXTENSION(AngelFit)) <CBPeripheralDelegate>
@end


SWIFT_CLASS_NAMED("UnitSetting")
@interface UnitSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UnitSetting (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t firstDayOfTheWeek;
@property (nonatomic) BOOL isSyncedToServer;
@property (nonatomic) BOOL isTimeFormat24H;
@property (nonatomic) int16_t lang;
@property (nonatomic, copy) NSString * _Nullable metricBritishUnit;
@property (nonatomic) int16_t stride100TimesCM;
@property (nonatomic, copy) NSString * _Nullable tempUint;
@property (nonatomic, strong) User * _Nullable user;
@end

typedef SWIFT_ENUM(NSInteger, UnitType) {
  UnitTypeDistance_KM = 0,
  UnitTypeDistance_MI = 1,
  UnitTypeWeight_KG = 2,
  UnitTypeWeight_LB = 3,
  UnitTypeTemp_C = 4,
  UnitTypeTemp_F = 5,
  UnitTypeLangure_ZH = 6,
  UnitTypeLangure_EN = 7,
  UnitTypeTimeFormat_24 = 8,
  UnitTypeTimeFormat_12 = 9,
};


SWIFT_CLASS_NAMED("User")
@interface User : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class UserSyncToServerLog;

@interface User (SWIFT_EXTENSION(AngelFit))
- (void)addUserSyncToServerLogListObject:(UserSyncToServerLog * _Nonnull)value;
- (void)removeUserSyncToServerLogListObject:(UserSyncToServerLog * _Nonnull)value;
- (void)addUserSyncToServerLogList:(NSSet * _Nonnull)values;
- (void)removeUserSyncToServerLogList:(NSSet * _Nonnull)values;
@end


@interface User (SWIFT_EXTENSION(AngelFit))
- (void)addMindBodyStateListObject:(MindBodyState * _Nonnull)value;
- (void)removeMindBodyStateListObject:(MindBodyState * _Nonnull)value;
- (void)addMindBodyStateList:(NSSet * _Nonnull)values;
- (void)removeMindBodyStateList:(NSSet * _Nonnull)values;
@end

@class WeightData;

@interface User (SWIFT_EXTENSION(AngelFit))
- (void)addWeightDataListObject:(WeightData * _Nonnull)value;
- (void)removeWeightDataListObject:(WeightData * _Nonnull)value;
- (void)addWeightDataList:(NSSet * _Nonnull)values;
- (void)removeWeightDataList:(NSSet * _Nonnull)values;
@end


@interface User (SWIFT_EXTENSION(AngelFit))
- (void)addDeviceListObject:(Device * _Nonnull)value;
- (void)removeDeviceListObject:(Device * _Nonnull)value;
- (void)addDeviceList:(NSSet * _Nonnull)values;
- (void)removeDeviceList:(NSSet * _Nonnull)values;
@end


@interface User (SWIFT_EXTENSION(AngelFit))
- (void)addUserActivityListObject:(UserActivity * _Nonnull)value;
- (void)removeUserActivityListObject:(UserActivity * _Nonnull)value;
- (void)addUserActivityList:(NSSet * _Nonnull)values;
- (void)removeUserActivityList:(NSSet * _Nonnull)values;
@end

@class UserFamily;
@class UserInfo;
@class UserPhoneInfo;

@interface User (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic) int64_t userId;
@property (nonatomic, strong) NSSet * _Nullable deviceList;
@property (nonatomic, strong) Goal * _Nullable goal;
@property (nonatomic, strong) NSSet * _Nullable mindBodyStateList;
@property (nonatomic, strong) UnitSetting * _Nullable unitSetting;
@property (nonatomic, strong) NSSet * _Nullable userActivityList;
@property (nonatomic, strong) UserFamily * _Nullable userFamily;
@property (nonatomic, strong) UserInfo * _Nullable userInfo;
@property (nonatomic, strong) UserPhoneInfo * _Nullable userPhoneInfo;
@property (nonatomic, strong) NSSet * _Nullable userSyncToServerLogList;
@property (nonatomic, strong) NSSet * _Nullable weightDataList;
@end


SWIFT_CLASS_NAMED("UserActivity")
@interface UserActivity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class UserActivityComment;

@interface UserActivity (SWIFT_EXTENSION(AngelFit))
- (void)addUserActivityCommentListObject:(UserActivityComment * _Nonnull)value;
- (void)removeUserActivityCommentListObject:(UserActivityComment * _Nonnull)value;
- (void)addUserActivityCommentList:(NSSet * _Nonnull)values;
- (void)removeUserActivityCommentList:(NSSet * _Nonnull)values;
@end

@class UserActivityLiker;

@interface UserActivity (SWIFT_EXTENSION(AngelFit))
- (void)addUserActivityLikerListObject:(UserActivityLiker * _Nonnull)value;
- (void)removeUserActivityLikerListObject:(UserActivityLiker * _Nonnull)value;
- (void)addUserActivityLikerList:(NSSet * _Nonnull)values;
- (void)removeUserActivityLikerList:(NSSet * _Nonnull)values;
@end


@interface UserActivity (SWIFT_EXTENSION(AngelFit))
- (void)addDoctorHaSuggestionListObject:(DoctorHaSuggestion * _Nonnull)value;
- (void)removeDoctorHaSuggestionListObject:(DoctorHaSuggestion * _Nonnull)value;
- (void)addDoctorHaSuggestionList:(NSSet * _Nonnull)values;
- (void)removeDoctorHaSuggestionList:(NSSet * _Nonnull)values;
@end


@interface UserActivity (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t comments;
@property (nonatomic) int32_t id;
@property (nonatomic) int16_t lastLikeEmotion;
@property (nonatomic) int16_t likes;
@property (nonatomic) int64_t objectId;
@property (nonatomic) int16_t type;
@property (nonatomic, strong) NSSet * _Nullable doctorHaSuggestionList;
@property (nonatomic, strong) User * _Nullable user;
@property (nonatomic, strong) NSSet * _Nullable userActivityCommentList;
@property (nonatomic, strong) NSSet * _Nullable userActivityLikerList;
@end


SWIFT_CLASS_NAMED("UserActivityComment")
@interface UserActivityComment : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserActivityComment (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int64_t fromWhomId;
@property (nonatomic) int64_t id;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) int64_t userId;
@property (nonatomic, strong) UserActivity * _Nullable userActivity;
@end


SWIFT_CLASS_NAMED("UserActivityLiker")
@interface UserActivityLiker : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserActivityLiker (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int16_t id;
@property (nonatomic) int64_t likeUserId;
@property (nonatomic) int16_t type;
@property (nonatomic, strong) UserActivity * _Nullable userActivity;
@end


SWIFT_CLASS_NAMED("UserDataInServerLog")
@interface UserDataInServerLog : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserDataInServerLog (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, strong) NSDate * _Nullable fromTime;
@property (nonatomic, strong) NSDate * _Nullable lastUpdatedTime;
@property (nonatomic, strong) NSDate * _Nullable toTime;
@property (nonatomic) int64_t userId;
@end


SWIFT_CLASS_NAMED("UserFamily")
@interface UserFamily : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserFamily (SWIFT_EXTENSION(AngelFit))
- (void)addUsersObject:(User * _Nonnull)value;
- (void)removeUsersObject:(User * _Nonnull)value;
- (void)addUsers:(NSSet * _Nonnull)values;
- (void)removeUsers:(NSSet * _Nonnull)values;
@end


@interface UserFamily (SWIFT_EXTENSION(AngelFit))
@property (nonatomic) int64_t isOnlineUserId;
@property (nonatomic) BOOL isSyncedToServer;
@property (nonatomic) int64_t userId;
@property (nonatomic, strong) NSSet * _Nullable users;
@end


SWIFT_CLASS_NAMED("UserInfo")
@interface UserInfo : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserInfo (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic) int16_t bindedDeviceCount;
@property (nonatomic, strong) NSDate * _Nullable birthday;
@property (nonatomic) int16_t gender;
@property (nonatomic) int16_t height100TimesCM;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, copy) NSString * _Nullable showName;
@property (nonatomic) int32_t weight10000TimesKG;
@property (nonatomic, strong) User * _Nullable user;
@end


SWIFT_CLASS_NAMED("UserPhoneInfo")
@interface UserPhoneInfo : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserPhoneInfo (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, copy) NSString * _Nullable system;
@property (nonatomic, copy) NSString * _Nullable systemVersion;
@property (nonatomic, strong) User * _Nullable user;
@end


SWIFT_CLASS_NAMED("UserSyncToServerLog")
@interface UserSyncToServerLog : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UserSyncToServerLog (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, strong) NSDate * _Nullable fromTime;
@property (nonatomic, strong) NSDate * _Nullable lastSyncTime;
@property (nonatomic, strong) NSDate * _Nullable toTime;
@property (nonatomic, strong) User * _Nullable user;
@end


SWIFT_CLASS_NAMED("WeightData")
@interface WeightData : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface WeightData (SWIFT_EXTENSION(AngelFit))
@property (nonatomic, strong) NSDate * _Nullable date;
@property (nonatomic) int64_t objectId;
@property (nonatomic) int32_t weight10000TimesKG;
@property (nonatomic, strong) User * _Nullable user;
@end

#pragma clang diagnostic pop
